### PR TITLE
Add indentation support for the ternary operator

### PR DESCRIPTION
**Pull request by ryan-workFromHome**
If the previous line is a ternary operation with an "=" assignment, the indentation will be at the word after that "=".
If the previous line is a ternary operation without an "=" assignment, the indentation will be at the word after the character "?".

### CODE REVIEW

**Comment by nachumk** [comment]
I tried out your code and I can't get it working the way you've described. Can you please provide a source code example and your .vimrc so I can try out your changes.

**Comment by ryan-workFromHome** [comment]
I noticed that my modification is not entirely working as expected under some specific contexts.
I might need some more time to look into it.

BTW, Although the master version in my forked branch has the same version as yours, those modification behaves more correctly with the old V1.12 codes.
With the V1.13, the indentation seems to have 1 extra tab than it really needs.

**Comment by nachumk** [comment]
Hi Ryan,
Can you please give some examples showing what is behaving incorrectly (or not as desired). Put the code in the comment so I can see what your changes do.
Thanks!

**Comment by ryan-workFromHome** [comment]
Hi Noah,
Thank you for emailing me.
I've closed the issue I raised a couple of weeks ago.

Thanks,
Ryan

**Pull request closed without merging**
